// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// aMatrix
NumericVector aMatrix(NumericMatrix A, IntegerVector s, IntegerVector d);
RcppExport SEXP pedyR_aMatrix(SEXP ASEXP, SEXP sSEXP, SEXP dSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericMatrix >::type A(ASEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type s(sSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type d(dSEXP);
    __result = Rcpp::wrap(aMatrix(A, s, d));
    return __result;
END_RCPP
}
// calcGen
IntegerVector calcGen(IntegerVector s, IntegerVector d, int nrow, IntegerVector genVec);
RcppExport SEXP pedyR_calcGen(SEXP sSEXP, SEXP dSEXP, SEXP nrowSEXP, SEXP genVecSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< IntegerVector >::type s(sSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type d(dSEXP);
    Rcpp::traits::input_parameter< int >::type nrow(nrowSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type genVec(genVecSEXP);
    __result = Rcpp::wrap(calcGen(s, d, nrow, genVec));
    return __result;
END_RCPP
}
