# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

aMatrix <- function(A, s, d) {
    .Call('pedyR_aMatrix', PACKAGE = 'pedyR', A, s, d)
}

calcGen <- function(s, d, nrow, genVec) {
    .Call('pedyR_calcGen', PACKAGE = 'pedyR', s, d, nrow, genVec)
}

